<?php

/** $viewModel \RCFerreira\InventoryPrice\ViewModel\InventorySection */

$viewModel = $block->getViewInventoryPrice();
$results = $viewModel->getSectionData();

?>
<div class="inventory-price-section">
    <select id="inventoryPriceOption" name="inventoryPriceOption">
        <option value=""></option>
        <?php foreach ($results as $value): ?>
        <option value="<?= $value['key'] ?>" data-percentage="<?= $value['percentage'] ?>" ><?= $value['value'] ?></option>
        <?php endforeach; ?>
    </select>
</div>
